<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
        <title>Hprose Api seed</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    </head>
    <body>
        <div class="container">
            <div class="page-header">
                <h1>Hprose Api</h1>
            </div>

            <div class="panel panel-info">
                <div class="panel-heading">
                    Hprose and Phalcon
                </div>
                <div class="panel-body">
                    <p><mark>Hprose</mark> is a High Performance Remote Object Service Engine.</p>

                    <p>It is a modern, lightweight, cross-language, cross-platform, object-oriented, high performance, <br>
                        remote dynamic communication middleware.
                        It is not only easy to use, but powerful.<br>
                        Get hprose <code>https://github.com/hprose</code>
                    </p>

                    <p><ul>
                        <li><a href="/api">View api methods list</a></li>
                        <li><a href="/docs/index.html">View api methods documentation.</a></li>
                    </ul></p>
                </div>
                <div class="panel-footer">
                    <small>Processing time: <?php echo processing_time(APP_START);?> seconds.</small>
                </div>
            </div>
        </div>
    </body>
</html>
